### ISSUE TITLE
No Purge

### ISSUE THREAD

**Issue by darkside-e** [notiz-dev/ngx-tailwind#12]
Hello,

I just saw tailwind the other day and wanted to merge it with angular which lead me here.

I wanted to first try to purge the CSS before I start with the app, but the problem I faced was that there was no purge happening when building for production and angular would give me the following error.

```
> NODE_ENV=production & ng build --prod

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
√ Browser application bundle generation complete.

Warning: budgets: initial exceeded maximum budget. Budget 500.00 kB was not met by 3.35 MB with a total of 3.84 MB.

Error: budgets: initial exceeded maximum budget. Budget 1.00 MB was not met by 2.84 MB with a total of 3.84 MB.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-tailwind-components@0.0.0 build:prod: `NODE_ENV=production & ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-tailwind-components@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Extra Info:
- OS: Windows 10
- Node: 14.15.0
- Angular 11

#### Install dotenv
`npm install dotenv -D`

#### Update `tailwind.config`
```
require('dotenv').config();
const enablePurge = process.env.NODE_ENV || false;

module.exports = {
  purge: {
    enabled: enablePurge,
    content: [
      './src/**/*.html',
      './src/**/*.ts'
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

#### Update `package.json`
add `SET` in build:prod script command
```
{
    ...
    "scripts": {
        ...    
        "build:prod": "SET NODE_ENV=production & ng build --prod"
    },
    ...
}
```

### Result
```
> SET NODE_ENV=production & ng build --prod

√ Browser application bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.f67b3d0dbce69012d3b2.js      | main          | 182.19 kB
polyfills.8c151b8375e767ff858f.js | polyfills     |  36.00 kB
styles.37982bb62c8e9ed08b5e.js    | styles        |  14.70 kB
runtime.39392f927e7c9fd727c8.js   | runtime       |   1.45 kB

                                  | Initial Total | 234.34 kB

Build at: 2020-12-19T20:06:20.841Z - Hash: 58b2ca811974ccd8d53e - Time: 13798ms
```

**Note**: I don't know if this can be considered an issue or not, but I hope it helps anyone who faces the same problem.

**Comment by stuartkuentzel** [comment]
I encountered the same problem. For me, not sure why, using the `enablePurge` with dotenv wasn't working. Included the `SET NODE_ENV=production` in the build process. To get it working for me, I just set the value to always be true. 
```
module.exports = {
  purge: {
    enabled: true, // set static
...
```
The issue I found with this though is, on `ng serve`, if a class is added that wasn't included in the initial build, it won't recognize the style.

**Comment by marcjulian** [comment]
@darkside-e thanks for reporting this issue on Windows. There might be a solution to use the package [cross-env]() so that setting `NODE_ENV=production` works across platforms like Windows as well as on Mac and Linux.

Can you try if it works with the following script and cross-env deps?

```json
{
  "scripts": {
     "build:prod": "cross-env NODE_ENV=production ng build --prod"
     ...
  },
  "devDependencies": {
    ...
    "cross-env": "^7.0.3",
  }
}
```

**Comment by danielehrhardt** [comment]
> @darkside-e thanks for reporting this issue on Windows. There might be a solution to use the package cross-env so that setting `NODE_ENV=production` works across platforms like Windows as well as on Mac and Linux.
> 
> Can you try if it works with the following script and cross-env deps?
> 
> ```json
> {
>   "scripts": {
>      "build:prod": "cross-env NODE_ENV=production ng build --prod"
>      ...
>   },
>   "devDependencies": {
>     ...
>     "cross-env": "^7.0.3",
>   }
> }
> ```
> 
> @stuartkuentzel yes enabling purge by default also effects `ng serve`. Can you give it a try with the above approach?
Work.

**Comment by darkside-e** [comment]
@marcjulian, sorry for the late response. Yes, I just tried it and it worked successfully as @danielehrhardt said. Thanks!

**Comment by marcjulian** [comment]
Should I include this in the schematics under a flag like `--installCrossPlatform`

**Comment by cruzelante098** [comment]
> Should I include this in the schematics under a flag like `--installCrossPlatform`?

That actually would be a great idea; I came to this very issue when my prod build went to ~3mb and was looking for a cross-platform solution.

**Comment by danielehrhardt** [comment]
> Should I include this in the schematics under a flag like `--installCrossPlatform`?

It should be a default.

**Comment by marcjulian** [comment]
It is added in the latest release [1.2.0](https://github.com/notiz-dev/ngx-tailwind/releases/tag/v.1.2.0). Thanks to @fcruzel for contribution!

**Comment by RaimonxDev** [comment]
Hello I have the following problem, Purge is not working for me, it generates a 2.92 mb css and I don't know how to solve it. I also have universal angular, everything is updated to version 11 

the command I run is npm run - --prod

![image](https://user-images.githubusercontent.com/39868803/106028390-a42c3700-60aa-11eb-8863-253d3440cfc0.png)
![image](https://user-images.githubusercontent.com/39868803/106028473-c0c86f00-60aa-11eb-8a38-885d51fa96ce.png)

I hope someone can help me, l Thanks

**Comment by fcruzel** [comment]
@RaimonxDev by the output of npm it does not seem that it's executing the `build:prod` script. Instead, npm it's running the command `ng build "--prod"` which won't execute PurgeCSS because `NODE_ENV` is not set, giving you that 2.92 mb CSS.

Could you please run the next command instead? 

```bash
npm run build:prod
```

**Comment by RaimonxDev** [comment]
that's right. and works

![image](https://user-images.githubusercontent.com/39868803/106032377-2a4a7c80-60af-11eb-8241-38c98a5c7f0d.png)


but when running` ng build: ssr` or `npm run build:ssr.` 
the css weighs 2.92 again
![image](https://user-images.githubusercontent.com/39868803/106032411-33d3e480-60af-11eb-8417-ac652ffbde0b.png)

**Comment by fcruzel** [comment]
You need to set `NODE_ENV=production` for PurgeCSS to work. I don't know if this behavior can be modified to work in all cases or under a different environment variable/value.
