### ISSUE TITLE
Incorrect tailwind directives when cssFormat=css

### ISSUE THREAD

**Issue by carmanchris31** [notiz-dev/ngx-tailwind#21]
**Problem:**
Schematic is inserting directives for scss even when cssFormat=css
```css
@tailwind 'tailwindcss/base';

@tailwind 'tailwindcss/components';

@tailwind 'tailwindcss/utilities';
```

This results in none of the tailwind styles being included in `src/styles.css`

**Expected behavior:**
Schematic should add this instead when cssFormat=css
```css
@tailwind base;

@tailwind components;

@tailwind utilities;
```

**References:**
- https://tailwindcss.com/docs/adding-base-styles#using-css
- https://dev.to/angular/setup-tailwindcss-in-angular-the-easy-way-1i5l#:~:text=if%20you%20are%20using%20css%20not%20scss%2C%20your%20file%20should%20look%20like%20this%3A

**Comment by marcjulian** [comment]
@carmanchris31 thanks for reporting. Should be fixed in https://github.com/notiz-dev/ngx-tailwind/releases/tag/v2.2.1
